version: "3.3"

services:
bot:
  build: ./
  image: local/jambo
  container_name: "jambo-container"
  restart: always
  environment:
    - TOKEN=[YOUR_TOKEN_HERE]
    - DEFAULT_GUILD=[GUILD_ID]
  volumes:
    - "./data:/app/data"