version: "3.3"

services:
bot:
  build: ./
  image: ghcr.io/cowoding-jams/jambo:latest
  container_name: "jambo-container"
  restart: always
  environment:
    - TOKEN=[YOUR_TOKEN_HERE]
    - DEFAULT_GUILD=[GUILD_ID]
  volumes:
    - "./data:/app/data"
  watchtower:
    image: containrrr/watchtower
    command: jambo --cleanup --interval 300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
